name: check
on:
  push: 
    branches:
      - master
  pull_request:
    branches:
      - master 
  schedule:
    - cron: "0 8 * * *"

jobs:
  test:
    name: test ${{ matrix.py }} - ${{ matrix.os }}
    runs-on: ${{ matrix.os }}-latest
    strategy:
      fail-fast: false
      matrix:
        os:
          - Ubuntu
        py:
          - "3.11"
          - "3.10"

    steps:
      - name: Setup python for test ${{ matrix.py }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.py }}
      - uses: actions/checkout@v4
      - name: Install module
        run: python -m pip install .[test]
      - name: run pytest
        run: pytest

